### ISSUE TITLE
no-brand-check IS NOT WORKING [BUG]

### ISSUE THREAD

**Issue by HonzasikCZ** [GigaZelensky/AntiSpoof#5]
Even when it's on, it doesn't write anything, even on discord

**Comment by GigaZelensky** [comment]
What do you mean by that? When you check their brand, what pops up?

**Comment by GigaZelensky** [comment]
Aha! i know what is happening, the no-brand check detects if a player is sending no brand plugin channel (minecraft:brand), which you can achieve by enabling "Block Channels" on Meteor client. But if a player IS sending a brand channel, but with an empty/blank string, they are technically still sending that minecraft:brand channel. To flag people using an empty brand, you can just add this simple entry to the config under `client-brands.brands`:

```
    blankbrand:
      enabled: true
      values:
        - "^$" # Regex for empty.blank brand string
      flag: true
      alert: true
      discord-alert: true
      alert-message: "&8[&eAntiSpoof&8] &7%player% &eis using a blank brand"
      console-alert-message: "%player% is using a blank brand"
      punish: false
      punishments: []
```

**Comment by GigaZelensky** [comment]
Aha, figured it out.

* **Why the check looks broken:**  
  `no-brand-check` only yells when the client completely skips the `minecraft:brand` channel. Meteor’s “Block Channels” does that, so the alert fires.  
  But if the channel **is** sent with an **empty string**, the plugin treats it as “brand present → all good,” so nothing shows up in chat or Discord. That’s why your blank-brand Meteor test sailed right through.

* **Stop the problem:**  
  Tell AntiSpoof that an empty brand is just as shady as no brand at all. Drop this under `client-brands.brands` in the config:

  ```yaml
  blankbrand:
    enabled: true
    values:
      - "^$"   # regex for empty/blank brand
    flag: true
    alert: true
    discord-alert: true
    alert-message: "&8[&eAntiSpoof&8] &7%player% &eis using a blank brand"
    console-alert-message: "%player% is using a blank brand"
    punish: false
    punishments: []
  ```

Reload the plugin, connect with Meteor using a blank brand, and you’ll get the alerts instead of silence.
